### ISSUE TITLE
Just Passwall 2 

### ISSUE THREAD

**Issue by Freemilan** [peditx/EZpasswall#2]
Hi guys , can you tell & teach me about how can install just passwall2 ? because when download says failed to download from 
((https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/arm_cortex-a7_neon-vfpv4/passwall_packages/Packages.gz )) ,

**Comment by peditx** [comment]
```bash
rm -f ezp.sh && wget https://raw.githubusercontent.com/peditx/EZpasswall/refs/heads/main/ezp.sh && chmod -X ezp.sh && sh ezp.sh
```
duh
